# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on: #[push, pull_request]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildWindows:
    runs-on: windows-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > nul
          haxelib install lime 7.9.0
          haxelib install openfl 9.1.0
          haxelib install flixel 4.11.0
          haxelib install flixel-tools 1.5.1
          haxelib install flixel-ui 2.5.0
          haxelib install flixel-addons 2.10.0
          haxelib install hxvlc
          haxelib install hscript
          haxelib install polymod
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib install hxcpp-debug-server
        shell: cmd
      - name: Set Haxelib Versions
        run: |
          haxelib set flixel-addons 2.10.0
          haxelib set flixel-tools 1.5.1
          haxelib set flixel-ui 2.5.0
          haxelib set lime 7.9.0
          haxelib set openfl 9.1.0
          haxelib set flixel 4.11.0
          haxelib list
      - name: Compile
        run: haxelib run lime build windows -D nightly
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: buildWindows
          path: export/release/windows/bin